@TodoApi_HostAddress = https://localhost:7074

POST {{TodoApi_HostAddress}}/todoitems

###
//creates a variable that is used for all of the endpoints.
@TodoApi_HostAddress = https://localhost:7047

# defines a POST request.
POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

GET {{TodoApi_HostAddress}}/todoitems

###
